export { ExampleUser } from 'src/__fixtures__/user/example-user'
export { ExampleActer } from 'src/__fixtures__/acter/example-acter'
export { GroupActerType } from 'src/__fixtures__/acter-type/group'
export { NetworkActerType } from 'src/__fixtures__/acter-type/network'
export { OrganizationActerType } from 'src/__fixtures__/acter-type/organization'
export { UserActerType } from 'src/__fixtures__/acter-type/user'
