"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertAccountArgs = exports.UpdateManyAccountArgs = exports.UpdateAccountArgs = exports.FindUniqueAccountArgs = exports.FindManyAccountArgs = exports.FindFirstAccountArgs = exports.DeleteManyAccountArgs = exports.DeleteAccountArgs = exports.CreateAccountArgs = exports.AggregateAccountArgs = void 0;
var AggregateAccountArgs_1 = require("./AggregateAccountArgs");
Object.defineProperty(exports, "AggregateAccountArgs", { enumerable: true, get: function () { return AggregateAccountArgs_1.AggregateAccountArgs; } });
var CreateAccountArgs_1 = require("./CreateAccountArgs");
Object.defineProperty(exports, "CreateAccountArgs", { enumerable: true, get: function () { return CreateAccountArgs_1.CreateAccountArgs; } });
var DeleteAccountArgs_1 = require("./DeleteAccountArgs");
Object.defineProperty(exports, "DeleteAccountArgs", { enumerable: true, get: function () { return DeleteAccountArgs_1.DeleteAccountArgs; } });
var DeleteManyAccountArgs_1 = require("./DeleteManyAccountArgs");
Object.defineProperty(exports, "DeleteManyAccountArgs", { enumerable: true, get: function () { return DeleteManyAccountArgs_1.DeleteManyAccountArgs; } });
var FindFirstAccountArgs_1 = require("./FindFirstAccountArgs");
Object.defineProperty(exports, "FindFirstAccountArgs", { enumerable: true, get: function () { return FindFirstAccountArgs_1.FindFirstAccountArgs; } });
var FindManyAccountArgs_1 = require("./FindManyAccountArgs");
Object.defineProperty(exports, "FindManyAccountArgs", { enumerable: true, get: function () { return FindManyAccountArgs_1.FindManyAccountArgs; } });
var FindUniqueAccountArgs_1 = require("./FindUniqueAccountArgs");
Object.defineProperty(exports, "FindUniqueAccountArgs", { enumerable: true, get: function () { return FindUniqueAccountArgs_1.FindUniqueAccountArgs; } });
var UpdateAccountArgs_1 = require("./UpdateAccountArgs");
Object.defineProperty(exports, "UpdateAccountArgs", { enumerable: true, get: function () { return UpdateAccountArgs_1.UpdateAccountArgs; } });
var UpdateManyAccountArgs_1 = require("./UpdateManyAccountArgs");
Object.defineProperty(exports, "UpdateManyAccountArgs", { enumerable: true, get: function () { return UpdateManyAccountArgs_1.UpdateManyAccountArgs; } });
var UpsertAccountArgs_1 = require("./UpsertAccountArgs");
Object.defineProperty(exports, "UpsertAccountArgs", { enumerable: true, get: function () { return UpsertAccountArgs_1.UpsertAccountArgs; } });
