import { GraphQLResolveInfo } from "graphql";
import { AggregateActivityArgs } from "./args/AggregateActivityArgs";
import { CreateActivityArgs } from "./args/CreateActivityArgs";
import { CreateManyActivityArgs } from "./args/CreateManyActivityArgs";
import { DeleteActivityArgs } from "./args/DeleteActivityArgs";
import { DeleteManyActivityArgs } from "./args/DeleteManyActivityArgs";
import { FindFirstActivityArgs } from "./args/FindFirstActivityArgs";
import { FindManyActivityArgs } from "./args/FindManyActivityArgs";
import { FindUniqueActivityArgs } from "./args/FindUniqueActivityArgs";
import { GroupByActivityArgs } from "./args/GroupByActivityArgs";
import { UpdateActivityArgs } from "./args/UpdateActivityArgs";
import { UpdateManyActivityArgs } from "./args/UpdateManyActivityArgs";
import { UpsertActivityArgs } from "./args/UpsertActivityArgs";
import { Activity } from "../../../models/Activity";
import { ActivityGroupBy } from "../../outputs/ActivityGroupBy";
import { AffectedRowsOutput } from "../../outputs/AffectedRowsOutput";
import { AggregateActivity } from "../../outputs/AggregateActivity";
export declare class ActivityCrudResolver {
    activity(ctx: any, info: GraphQLResolveInfo, args: FindUniqueActivityArgs): Promise<Activity | null>;
    findFirstActivity(ctx: any, info: GraphQLResolveInfo, args: FindFirstActivityArgs): Promise<Activity | null>;
    activities(ctx: any, info: GraphQLResolveInfo, args: FindManyActivityArgs): Promise<Activity[]>;
    createActivity(ctx: any, info: GraphQLResolveInfo, args: CreateActivityArgs): Promise<Activity>;
    createManyActivity(ctx: any, info: GraphQLResolveInfo, args: CreateManyActivityArgs): Promise<AffectedRowsOutput>;
    deleteActivity(ctx: any, info: GraphQLResolveInfo, args: DeleteActivityArgs): Promise<Activity | null>;
    updateActivity(ctx: any, info: GraphQLResolveInfo, args: UpdateActivityArgs): Promise<Activity | null>;
    deleteManyActivity(ctx: any, info: GraphQLResolveInfo, args: DeleteManyActivityArgs): Promise<AffectedRowsOutput>;
    updateManyActivity(ctx: any, info: GraphQLResolveInfo, args: UpdateManyActivityArgs): Promise<AffectedRowsOutput>;
    upsertActivity(ctx: any, info: GraphQLResolveInfo, args: UpsertActivityArgs): Promise<Activity>;
    aggregateActivity(ctx: any, info: GraphQLResolveInfo, args: AggregateActivityArgs): Promise<AggregateActivity>;
    groupByActivity(ctx: any, info: GraphQLResolveInfo, args: GroupByActivityArgs): Promise<ActivityGroupBy[]>;
}
