"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertPostArgs = exports.UpdatePostArgs = exports.UpdateManyPostArgs = exports.GroupByPostArgs = exports.FindUniquePostArgs = exports.FindManyPostArgs = exports.FindFirstPostArgs = exports.DeletePostArgs = exports.DeleteManyPostArgs = exports.CreatePostArgs = exports.CreateManyPostArgs = exports.AggregatePostArgs = void 0;
var AggregatePostArgs_1 = require("./AggregatePostArgs");
Object.defineProperty(exports, "AggregatePostArgs", { enumerable: true, get: function () { return AggregatePostArgs_1.AggregatePostArgs; } });
var CreateManyPostArgs_1 = require("./CreateManyPostArgs");
Object.defineProperty(exports, "CreateManyPostArgs", { enumerable: true, get: function () { return CreateManyPostArgs_1.CreateManyPostArgs; } });
var CreatePostArgs_1 = require("./CreatePostArgs");
Object.defineProperty(exports, "CreatePostArgs", { enumerable: true, get: function () { return CreatePostArgs_1.CreatePostArgs; } });
var DeleteManyPostArgs_1 = require("./DeleteManyPostArgs");
Object.defineProperty(exports, "DeleteManyPostArgs", { enumerable: true, get: function () { return DeleteManyPostArgs_1.DeleteManyPostArgs; } });
var DeletePostArgs_1 = require("./DeletePostArgs");
Object.defineProperty(exports, "DeletePostArgs", { enumerable: true, get: function () { return DeletePostArgs_1.DeletePostArgs; } });
var FindFirstPostArgs_1 = require("./FindFirstPostArgs");
Object.defineProperty(exports, "FindFirstPostArgs", { enumerable: true, get: function () { return FindFirstPostArgs_1.FindFirstPostArgs; } });
var FindManyPostArgs_1 = require("./FindManyPostArgs");
Object.defineProperty(exports, "FindManyPostArgs", { enumerable: true, get: function () { return FindManyPostArgs_1.FindManyPostArgs; } });
var FindUniquePostArgs_1 = require("./FindUniquePostArgs");
Object.defineProperty(exports, "FindUniquePostArgs", { enumerable: true, get: function () { return FindUniquePostArgs_1.FindUniquePostArgs; } });
var GroupByPostArgs_1 = require("./GroupByPostArgs");
Object.defineProperty(exports, "GroupByPostArgs", { enumerable: true, get: function () { return GroupByPostArgs_1.GroupByPostArgs; } });
var UpdateManyPostArgs_1 = require("./UpdateManyPostArgs");
Object.defineProperty(exports, "UpdateManyPostArgs", { enumerable: true, get: function () { return UpdateManyPostArgs_1.UpdateManyPostArgs; } });
var UpdatePostArgs_1 = require("./UpdatePostArgs");
Object.defineProperty(exports, "UpdatePostArgs", { enumerable: true, get: function () { return UpdatePostArgs_1.UpdatePostArgs; } });
var UpsertPostArgs_1 = require("./UpsertPostArgs");
Object.defineProperty(exports, "UpsertPostArgs", { enumerable: true, get: function () { return UpsertPostArgs_1.UpsertPostArgs; } });
