export const ACTIVITIES = 'activities'
export const FEED = 'feed'
export const FORUM = 'forum'
export const MEMBERS = 'members'
export const SETTINGS = 'settings'
export const PEOPLE = 'people'
export const ORGANISATIONS = 'organisations'
