export const DATE_FORMAT = 'ddd, D MMM YYYY HH:mm'
export const DATE_FORMAT_NO_TIME = 'ddd, D MMM YYYY'
export const DATE_FORMAT_SHORT = 'D MMM. HH:mm'
export const DATE_FORMAT_LONG = 'DD.MM.YYYY HH:mm'
export const DATE_FORMAT_SHORT_NO_TIME = 'D MMM.'
