export const ACTIVITY = 'activity'
export const ACTIVITIES = 'activities'
export const FORUM = 'forum'
export const GROUP = 'group'
export const ORGANISATION = 'organisation'
export const MEMBERS = 'members'
export const NETWORK = 'network'
export const USER = 'user'
