import { ActerAvgOrderByAggregateInput } from "../inputs/ActerAvgOrderByAggregateInput";
import { ActerCountOrderByAggregateInput } from "../inputs/ActerCountOrderByAggregateInput";
import { ActerMaxOrderByAggregateInput } from "../inputs/ActerMaxOrderByAggregateInput";
import { ActerMinOrderByAggregateInput } from "../inputs/ActerMinOrderByAggregateInput";
import { ActerSumOrderByAggregateInput } from "../inputs/ActerSumOrderByAggregateInput";
export declare class ActerOrderByWithAggregationInput {
    id?: "asc" | "desc" | undefined;
    acterTypeId?: "asc" | "desc" | undefined;
    name?: "asc" | "desc" | undefined;
    slug?: "asc" | "desc" | undefined;
    description?: "asc" | "desc" | undefined;
    location?: "asc" | "desc" | undefined;
    locationLat?: "asc" | "desc" | undefined;
    locationLng?: "asc" | "desc" | undefined;
    url?: "asc" | "desc" | undefined;
    avatarUrl?: "asc" | "desc" | undefined;
    bannerUrl?: "asc" | "desc" | undefined;
    useAdmins?: "asc" | "desc" | undefined;
    createdAt?: "asc" | "desc" | undefined;
    updatedAt?: "asc" | "desc" | undefined;
    acterJoinSetting?: "asc" | "desc" | undefined;
    acterNotifySetting?: "asc" | "desc" | undefined;
    acterNotifyEmailFrequency?: "asc" | "desc" | undefined;
    acterPrivacySetting?: "asc" | "desc" | undefined;
    createdByUserId?: "asc" | "desc" | undefined;
    deletedAt?: "asc" | "desc" | undefined;
    deletedByUserId?: "asc" | "desc" | undefined;
    parentActerId?: "asc" | "desc" | undefined;
    _count?: ActerCountOrderByAggregateInput | undefined;
    _avg?: ActerAvgOrderByAggregateInput | undefined;
    _max?: ActerMaxOrderByAggregateInput | undefined;
    _min?: ActerMinOrderByAggregateInput | undefined;
    _sum?: ActerSumOrderByAggregateInput | undefined;
}
