import { BoolFieldUpdateOperationsInput } from "../inputs/BoolFieldUpdateOperationsInput";
import { DateTimeFieldUpdateOperationsInput } from "../inputs/DateTimeFieldUpdateOperationsInput";
import { EnumActerJoinSettingsFieldUpdateOperationsInput } from "../inputs/EnumActerJoinSettingsFieldUpdateOperationsInput";
import { EnumActerNotificationEmailFrequencyFieldUpdateOperationsInput } from "../inputs/EnumActerNotificationEmailFrequencyFieldUpdateOperationsInput";
import { EnumActerNotificationSettingsFieldUpdateOperationsInput } from "../inputs/EnumActerNotificationSettingsFieldUpdateOperationsInput";
import { EnumActerPrivacySettingsFieldUpdateOperationsInput } from "../inputs/EnumActerPrivacySettingsFieldUpdateOperationsInput";
import { NullableDateTimeFieldUpdateOperationsInput } from "../inputs/NullableDateTimeFieldUpdateOperationsInput";
import { NullableFloatFieldUpdateOperationsInput } from "../inputs/NullableFloatFieldUpdateOperationsInput";
import { NullableStringFieldUpdateOperationsInput } from "../inputs/NullableStringFieldUpdateOperationsInput";
import { StringFieldUpdateOperationsInput } from "../inputs/StringFieldUpdateOperationsInput";
export declare class ActerUpdateManyMutationInput {
    id?: StringFieldUpdateOperationsInput | undefined;
    name?: NullableStringFieldUpdateOperationsInput | undefined;
    slug?: NullableStringFieldUpdateOperationsInput | undefined;
    description?: NullableStringFieldUpdateOperationsInput | undefined;
    location?: NullableStringFieldUpdateOperationsInput | undefined;
    locationLat?: NullableFloatFieldUpdateOperationsInput | undefined;
    locationLng?: NullableFloatFieldUpdateOperationsInput | undefined;
    url?: NullableStringFieldUpdateOperationsInput | undefined;
    avatarUrl?: NullableStringFieldUpdateOperationsInput | undefined;
    bannerUrl?: NullableStringFieldUpdateOperationsInput | undefined;
    useAdmins?: BoolFieldUpdateOperationsInput | undefined;
    createdAt?: DateTimeFieldUpdateOperationsInput | undefined;
    updatedAt?: DateTimeFieldUpdateOperationsInput | undefined;
    acterJoinSetting?: EnumActerJoinSettingsFieldUpdateOperationsInput | undefined;
    acterNotifySetting?: EnumActerNotificationSettingsFieldUpdateOperationsInput | undefined;
    acterNotifyEmailFrequency?: EnumActerNotificationEmailFrequencyFieldUpdateOperationsInput | undefined;
    acterPrivacySetting?: EnumActerPrivacySettingsFieldUpdateOperationsInput | undefined;
    deletedAt?: NullableDateTimeFieldUpdateOperationsInput | undefined;
}
