import { ActerConnectionOrderByRelationAggregateInput } from "../inputs/ActerConnectionOrderByRelationAggregateInput";
import { ActerInterestOrderByRelationAggregateInput } from "../inputs/ActerInterestOrderByRelationAggregateInput";
import { ActerOrderByRelationAggregateInput } from "../inputs/ActerOrderByRelationAggregateInput";
import { ActerTypeOrderByWithRelationInput } from "../inputs/ActerTypeOrderByWithRelationInput";
import { ActivityOrderByRelationAggregateInput } from "../inputs/ActivityOrderByRelationAggregateInput";
import { ActivityOrderByWithRelationInput } from "../inputs/ActivityOrderByWithRelationInput";
import { InviteOrderByRelationAggregateInput } from "../inputs/InviteOrderByRelationAggregateInput";
import { LinkOrderByRelationAggregateInput } from "../inputs/LinkOrderByRelationAggregateInput";
import { NotificationOrderByRelationAggregateInput } from "../inputs/NotificationOrderByRelationAggregateInput";
import { PostOrderByRelationAggregateInput } from "../inputs/PostOrderByRelationAggregateInput";
import { UserOrderByWithRelationInput } from "../inputs/UserOrderByWithRelationInput";
export declare class ActerOrderByWithRelationInput {
    id?: "asc" | "desc" | undefined;
    acterTypeId?: "asc" | "desc" | undefined;
    name?: "asc" | "desc" | undefined;
    slug?: "asc" | "desc" | undefined;
    description?: "asc" | "desc" | undefined;
    location?: "asc" | "desc" | undefined;
    locationLat?: "asc" | "desc" | undefined;
    locationLng?: "asc" | "desc" | undefined;
    url?: "asc" | "desc" | undefined;
    avatarUrl?: "asc" | "desc" | undefined;
    bannerUrl?: "asc" | "desc" | undefined;
    useAdmins?: "asc" | "desc" | undefined;
    createdAt?: "asc" | "desc" | undefined;
    updatedAt?: "asc" | "desc" | undefined;
    acterJoinSetting?: "asc" | "desc" | undefined;
    acterNotifySetting?: "asc" | "desc" | undefined;
    acterNotifyEmailFrequency?: "asc" | "desc" | undefined;
    acterPrivacySetting?: "asc" | "desc" | undefined;
    ActerInterests?: ActerInterestOrderByRelationAggregateInput | undefined;
    createdByUser?: UserOrderByWithRelationInput | undefined;
    createdByUserId?: "asc" | "desc" | undefined;
    deletedAt?: "asc" | "desc" | undefined;
    deletedByUserId?: "asc" | "desc" | undefined;
    DeletedByUser?: UserOrderByWithRelationInput | undefined;
    ActerType?: ActerTypeOrderByWithRelationInput | undefined;
    Parent?: ActerOrderByWithRelationInput | undefined;
    Children?: ActerOrderByRelationAggregateInput | undefined;
    parentActerId?: "asc" | "desc" | undefined;
    Following?: ActerConnectionOrderByRelationAggregateInput | undefined;
    Followers?: ActerConnectionOrderByRelationAggregateInput | undefined;
    User?: UserOrderByWithRelationInput | undefined;
    Activity?: ActivityOrderByWithRelationInput | undefined;
    ActivitiesOrganized?: ActivityOrderByRelationAggregateInput | undefined;
    AttachedPosts?: PostOrderByRelationAggregateInput | undefined;
    AuthoredPosts?: PostOrderByRelationAggregateInput | undefined;
    AttachedLinks?: LinkOrderByRelationAggregateInput | undefined;
    NotificationsTo?: NotificationOrderByRelationAggregateInput | undefined;
    NotificationsOn?: NotificationOrderByRelationAggregateInput | undefined;
    Invite?: InviteOrderByRelationAggregateInput | undefined;
}
