import { ActerConnectionListRelationFilter } from "../inputs/ActerConnectionListRelationFilter";
import { ActerInterestListRelationFilter } from "../inputs/ActerInterestListRelationFilter";
import { ActerListRelationFilter } from "../inputs/ActerListRelationFilter";
import { ActerRelationFilter } from "../inputs/ActerRelationFilter";
import { ActerTypeRelationFilter } from "../inputs/ActerTypeRelationFilter";
import { ActivityListRelationFilter } from "../inputs/ActivityListRelationFilter";
import { ActivityRelationFilter } from "../inputs/ActivityRelationFilter";
import { BoolFilter } from "../inputs/BoolFilter";
import { DateTimeFilter } from "../inputs/DateTimeFilter";
import { DateTimeNullableFilter } from "../inputs/DateTimeNullableFilter";
import { EnumActerJoinSettingsFilter } from "../inputs/EnumActerJoinSettingsFilter";
import { EnumActerNotificationEmailFrequencyFilter } from "../inputs/EnumActerNotificationEmailFrequencyFilter";
import { EnumActerNotificationSettingsFilter } from "../inputs/EnumActerNotificationSettingsFilter";
import { EnumActerPrivacySettingsFilter } from "../inputs/EnumActerPrivacySettingsFilter";
import { FloatNullableFilter } from "../inputs/FloatNullableFilter";
import { InviteListRelationFilter } from "../inputs/InviteListRelationFilter";
import { LinkListRelationFilter } from "../inputs/LinkListRelationFilter";
import { NotificationListRelationFilter } from "../inputs/NotificationListRelationFilter";
import { PostListRelationFilter } from "../inputs/PostListRelationFilter";
import { StringFilter } from "../inputs/StringFilter";
import { StringNullableFilter } from "../inputs/StringNullableFilter";
import { UserRelationFilter } from "../inputs/UserRelationFilter";
export declare class ActerWhereInput {
    AND?: ActerWhereInput[] | undefined;
    OR?: ActerWhereInput[] | undefined;
    NOT?: ActerWhereInput[] | undefined;
    id?: StringFilter | undefined;
    acterTypeId?: StringFilter | undefined;
    name?: StringNullableFilter | undefined;
    slug?: StringNullableFilter | undefined;
    description?: StringNullableFilter | undefined;
    location?: StringNullableFilter | undefined;
    locationLat?: FloatNullableFilter | undefined;
    locationLng?: FloatNullableFilter | undefined;
    url?: StringNullableFilter | undefined;
    avatarUrl?: StringNullableFilter | undefined;
    bannerUrl?: StringNullableFilter | undefined;
    useAdmins?: BoolFilter | undefined;
    createdAt?: DateTimeFilter | undefined;
    updatedAt?: DateTimeFilter | undefined;
    acterJoinSetting?: EnumActerJoinSettingsFilter | undefined;
    acterNotifySetting?: EnumActerNotificationSettingsFilter | undefined;
    acterNotifyEmailFrequency?: EnumActerNotificationEmailFrequencyFilter | undefined;
    acterPrivacySetting?: EnumActerPrivacySettingsFilter | undefined;
    ActerInterests?: ActerInterestListRelationFilter | undefined;
    createdByUser?: UserRelationFilter | undefined;
    createdByUserId?: StringFilter | undefined;
    deletedAt?: DateTimeNullableFilter | undefined;
    deletedByUserId?: StringNullableFilter | undefined;
    DeletedByUser?: UserRelationFilter | undefined;
    ActerType?: ActerTypeRelationFilter | undefined;
    Parent?: ActerRelationFilter | undefined;
    Children?: ActerListRelationFilter | undefined;
    parentActerId?: StringNullableFilter | undefined;
    Following?: ActerConnectionListRelationFilter | undefined;
    Followers?: ActerConnectionListRelationFilter | undefined;
    User?: UserRelationFilter | undefined;
    Activity?: ActivityRelationFilter | undefined;
    ActivitiesOrganized?: ActivityListRelationFilter | undefined;
    AttachedPosts?: PostListRelationFilter | undefined;
    AuthoredPosts?: PostListRelationFilter | undefined;
    AttachedLinks?: LinkListRelationFilter | undefined;
    NotificationsTo?: NotificationListRelationFilter | undefined;
    NotificationsOn?: NotificationListRelationFilter | undefined;
    Invite?: InviteListRelationFilter | undefined;
}
