import { ActerConnection } from "../models/ActerConnection";
import { ActerInterest } from "../models/ActerInterest";
import { ActerType } from "../models/ActerType";
import { Activity } from "../models/Activity";
import { Invite } from "../models/Invite";
import { Link } from "../models/Link";
import { Notification } from "../models/Notification";
import { Post } from "../models/Post";
import { User } from "../models/User";
import { ActerCount } from "../resolvers/outputs/ActerCount";
export declare class Acter {
    id: string;
    acterTypeId: string;
    name?: string | null;
    slug?: string | null;
    description?: string | null;
    location?: string | null;
    locationLat?: number | null;
    locationLng?: number | null;
    url?: string | null;
    avatarUrl?: string | null;
    bannerUrl?: string | null;
    useAdmins: boolean;
    createdAt: Date;
    updatedAt: Date;
    acterJoinSetting: "EVERYONE" | "RESTRICTED" | "INVITE_ONLY";
    acterNotifySetting: "ALL_ACTIVITY" | "NONE";
    acterNotifyEmailFrequency: "NEVER" | "DAILY" | "INSTANT";
    acterPrivacySetting: "PUBLIC" | "PRIVATE";
    ActerInterests?: ActerInterest[];
    createdByUser?: User;
    createdByUserId: string;
    deletedAt?: Date | null;
    deletedByUserId?: string | null;
    DeletedByUser?: User | null;
    ActerType?: ActerType;
    Parent?: Acter | null;
    Children?: Acter[];
    parentActerId?: string | null;
    Following?: ActerConnection[];
    Followers?: ActerConnection[];
    User?: User | null;
    Activity?: Activity | null;
    ActivitiesOrganized?: Activity[];
    AttachedPosts?: Post[];
    AuthoredPosts?: Post[];
    AttachedLinks?: Link[];
    NotificationsTo?: Notification[];
    NotificationsOn?: Notification[];
    Invite?: Invite[];
    _count?: ActerCount | null;
}
