import { GraphQLResolveInfo } from "graphql";
import { AggregateActerTypeRuleArgs } from "./args/AggregateActerTypeRuleArgs";
import { CreateActerTypeRuleArgs } from "./args/CreateActerTypeRuleArgs";
import { CreateManyActerTypeRuleArgs } from "./args/CreateManyActerTypeRuleArgs";
import { DeleteActerTypeRuleArgs } from "./args/DeleteActerTypeRuleArgs";
import { DeleteManyActerTypeRuleArgs } from "./args/DeleteManyActerTypeRuleArgs";
import { FindFirstActerTypeRuleArgs } from "./args/FindFirstActerTypeRuleArgs";
import { FindManyActerTypeRuleArgs } from "./args/FindManyActerTypeRuleArgs";
import { FindUniqueActerTypeRuleArgs } from "./args/FindUniqueActerTypeRuleArgs";
import { GroupByActerTypeRuleArgs } from "./args/GroupByActerTypeRuleArgs";
import { UpdateActerTypeRuleArgs } from "./args/UpdateActerTypeRuleArgs";
import { UpdateManyActerTypeRuleArgs } from "./args/UpdateManyActerTypeRuleArgs";
import { UpsertActerTypeRuleArgs } from "./args/UpsertActerTypeRuleArgs";
import { ActerTypeRule } from "../../../models/ActerTypeRule";
import { ActerTypeRuleGroupBy } from "../../outputs/ActerTypeRuleGroupBy";
import { AffectedRowsOutput } from "../../outputs/AffectedRowsOutput";
import { AggregateActerTypeRule } from "../../outputs/AggregateActerTypeRule";
export declare class ActerTypeRuleCrudResolver {
    acterTypeRule(ctx: any, info: GraphQLResolveInfo, args: FindUniqueActerTypeRuleArgs): Promise<ActerTypeRule | null>;
    findFirstActerTypeRule(ctx: any, info: GraphQLResolveInfo, args: FindFirstActerTypeRuleArgs): Promise<ActerTypeRule | null>;
    acterTypeRules(ctx: any, info: GraphQLResolveInfo, args: FindManyActerTypeRuleArgs): Promise<ActerTypeRule[]>;
    createActerTypeRule(ctx: any, info: GraphQLResolveInfo, args: CreateActerTypeRuleArgs): Promise<ActerTypeRule>;
    createManyActerTypeRule(ctx: any, info: GraphQLResolveInfo, args: CreateManyActerTypeRuleArgs): Promise<AffectedRowsOutput>;
    deleteActerTypeRule(ctx: any, info: GraphQLResolveInfo, args: DeleteActerTypeRuleArgs): Promise<ActerTypeRule | null>;
    updateActerTypeRule(ctx: any, info: GraphQLResolveInfo, args: UpdateActerTypeRuleArgs): Promise<ActerTypeRule | null>;
    deleteManyActerTypeRule(ctx: any, info: GraphQLResolveInfo, args: DeleteManyActerTypeRuleArgs): Promise<AffectedRowsOutput>;
    updateManyActerTypeRule(ctx: any, info: GraphQLResolveInfo, args: UpdateManyActerTypeRuleArgs): Promise<AffectedRowsOutput>;
    upsertActerTypeRule(ctx: any, info: GraphQLResolveInfo, args: UpsertActerTypeRuleArgs): Promise<ActerTypeRule>;
    aggregateActerTypeRule(ctx: any, info: GraphQLResolveInfo, args: AggregateActerTypeRuleArgs): Promise<AggregateActerTypeRule>;
    groupByActerTypeRule(ctx: any, info: GraphQLResolveInfo, args: GroupByActerTypeRuleArgs): Promise<ActerTypeRuleGroupBy[]>;
}
