import { GraphQLResolveInfo } from "graphql";
import { AggregateActerArgs } from "./args/AggregateActerArgs";
import { CreateActerArgs } from "./args/CreateActerArgs";
import { CreateManyActerArgs } from "./args/CreateManyActerArgs";
import { DeleteActerArgs } from "./args/DeleteActerArgs";
import { DeleteManyActerArgs } from "./args/DeleteManyActerArgs";
import { FindFirstActerArgs } from "./args/FindFirstActerArgs";
import { FindManyActerArgs } from "./args/FindManyActerArgs";
import { FindUniqueActerArgs } from "./args/FindUniqueActerArgs";
import { GroupByActerArgs } from "./args/GroupByActerArgs";
import { UpdateActerArgs } from "./args/UpdateActerArgs";
import { UpdateManyActerArgs } from "./args/UpdateManyActerArgs";
import { UpsertActerArgs } from "./args/UpsertActerArgs";
import { Acter } from "../../../models/Acter";
import { ActerGroupBy } from "../../outputs/ActerGroupBy";
import { AffectedRowsOutput } from "../../outputs/AffectedRowsOutput";
import { AggregateActer } from "../../outputs/AggregateActer";
export declare class ActerCrudResolver {
    acter(ctx: any, info: GraphQLResolveInfo, args: FindUniqueActerArgs): Promise<Acter | null>;
    findFirstActer(ctx: any, info: GraphQLResolveInfo, args: FindFirstActerArgs): Promise<Acter | null>;
    acters(ctx: any, info: GraphQLResolveInfo, args: FindManyActerArgs): Promise<Acter[]>;
    createActer(ctx: any, info: GraphQLResolveInfo, args: CreateActerArgs): Promise<Acter>;
    createManyActer(ctx: any, info: GraphQLResolveInfo, args: CreateManyActerArgs): Promise<AffectedRowsOutput>;
    deleteActer(ctx: any, info: GraphQLResolveInfo, args: DeleteActerArgs): Promise<Acter | null>;
    updateActer(ctx: any, info: GraphQLResolveInfo, args: UpdateActerArgs): Promise<Acter | null>;
    deleteManyActer(ctx: any, info: GraphQLResolveInfo, args: DeleteManyActerArgs): Promise<AffectedRowsOutput>;
    updateManyActer(ctx: any, info: GraphQLResolveInfo, args: UpdateManyActerArgs): Promise<AffectedRowsOutput>;
    upsertActer(ctx: any, info: GraphQLResolveInfo, args: UpsertActerArgs): Promise<Acter>;
    aggregateActer(ctx: any, info: GraphQLResolveInfo, args: AggregateActerArgs): Promise<AggregateActer>;
    groupByActer(ctx: any, info: GraphQLResolveInfo, args: GroupByActerArgs): Promise<ActerGroupBy[]>;
}
