[build]
command = 'yarn storybook-build'

[functions]
directory = '../functions'
node_bundler = 'esbuild'

[[redirects]]
from = '*'
to = '.netlify/functions/login'
status = 401
conditions = {Role = [!"admin"]}