// TODO: fix the below lint error
/* eslint no-irregular-whitespace: 0 */
import React from 'react'
import { NextPage } from 'next'
import { Layout } from '@acter/components/layout'
import { Head } from '@acter/components/layout/head'

const GDPR: NextPage = () => {
  return (
    <Layout>
      <Head title="Privacy Policy - Acter" />

      <main>
        <div>
          <h2> Privacy Policy</h2>
          <span>Last updated: February 24, 2021</span>
          <p>
            Acter (“we” or “us” or “our”) understands and respects the privacy
            of our users (“user” or “you”) This Privacy Policy explains how we
            collect, use, disclose, and safeguard your information when you
            visit our website https://www.acter.global including any other
            mobile website, or mobile application related or connected thereto
            (collectively, the “service”). We use Your Personal information to
            provide and improve the Service. By using the Service, You agree to
            the collection and use of information in accordance with this
            Privacy Policy. Please read this Privacy Policy carefully.
          </p>
          IF YOU DO NOT AGREE WITH THE TERMS OF THIS PRIVACY POLICY, PLEASE DO
          NOT ACCESS THE SITE.
          <h3> Interpretation and Definitions </h3>
          <h3> Interpretation </h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>
          ​<h3>Definitions</h3>
          <span>For the purposes of this Privacy Policy: </span>
          <ul>
            <li>
              Account means a unique account created for You to access our
              Service or parts of our Service.
            </li>
            <li>
              Company (referred to as either "the Company", "We", "Us" or "Our"
              in this Agreement) refers to Acter Aps, Skovgårde Bygade 11 A Hyl
              Skovgård 8400 Ebeltoft.
            </li>
            <li>
              Cookies are small files that are placed on Your computer, mobile
              device or any other device by a Web Application. containing the
              details of Your browsing history on that Web Application among its
              many uses.
            </li>
            <li>Country refers to: Denmark</li>
            <li>
              Device means any device that can access the Service such as a
              computer, a cell phone or a digital tablet.
            </li>
            <li>
              Personal Data is any information that relates to an identified or
              identifiable individual.
            </li>
            <li>Service refers to the Web Application.</li>
            <li>
              Service Provider means any natural or legal person who processes
              the data on behalf of the Company. It refers to third-party
              companies or individuals employed by the Company to facilitate the
              Service, to provide the Service on behalf of the Company, to
              perform services related to the Service or to assist the Company
              in analyzing how the Service is used.
            </li>
            <li>
              Third-party Social Media Service refers to any Web Application or
              any social network Web Application through which a User can log in
              or create an account to use the Service.
            </li>
            <li>
              Usage Data refers to data collected automatically, either
              generated by the use of the Service or from the Service
              infrastructure itself (for example, the duration of a page visit).
            </li>
            <li>
              Web Application refers to Acter, accessible from
              https://www.acter.global
            </li>
            <li>
              You, mean the individual accessing or using the Service, or the
              company, or other legal entity on behalf of which such individual
              is accessing or using the Service, as applicable.
            </li>
          </ul>
          <h3>Information collection and use</h3>
          <h4>Types of information collected:</h4>
          <h4>Personal information:</h4>
          <p>
            While using our service, we may ask you to provide us with certain
            personally identifiable information that may be relevant for the
            purpose of operating and providing our service to you, when you
            create an account and/or when you update your member profile. (the
            information we collect from you, to the extent that it is private,
            is disclosed only in accordance with this privacy policy.). our
            service will use the personal information you provide to: deliver
            the services of our website; communicate with you; respond to your
            questions, queries, concerns or complaints regarding our website
            and/or services; to research, analyze, develop, manage, protect and
            improve our services; and keep you up-to-date on our services and
            notify you of new offerings.
          </p>
          <p>
            Personally identifiable information may include, but is not limited
            to:
          </p>
          <ul>
            <li>email address</li>
            <li>first name and last name</li>
            <li>location</li>
            <li>usage data</li>
          </ul>
          <h4>Usage information:</h4>
          <p>
            Usage information may include information such as your device's
            internet protocol address (e.g. ip address), browser type, browser
            version, the pages of our service that you visit, the time and date
            of your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data. when you access the service
            by or through a mobile device, we may collect certain information
            automatically, including, but not limited to, the type of mobile
            device you use, your mobile device unique id, the ip address of your
            mobile device, your mobile operating system, the type of mobile
            internet browser you use, unique device identifiers and other
            diagnostic data.
          </p>
          <h4>Location data</h4>
          <p>
            We may use and store information about your location if you give us
            permission to do so (“location data”). we use this data to provide
            features of our service, to improve and customize our service. you
            can enable or disable location services when you use our service at
            any time, through your device settings.
          </p>
          <h4>Tracking & cookies data</h4>
          <p>
            We use cookies and similar tracking technologies to track the
            activity on our service and hold certain information. cookies are
            files with small amount of data which may include an anonymous
            unique identifier. cookies are sent to your browser from a website
            and stored on your device. tracking technologies also used are
            beacons, tags, and scripts to collect and track information and to
            improve and analyze our service. you can instruct your browser to
            refuse all cookies or to indicate when a cookie is being sent.
            however, if you do not accept cookies, you may not be able to use
            some portions of our service.
          </p>
          <p>examples of cookies we use:</p>
          <ul>
            <li>
              <strong>Session cookies.</strong>
              we use session cookies to operate our service.
            </li>
            <li>
              <strong>Security cookies.</strong>
              we use security cookies for security purposes.
            </li>
          </ul>
          <h3>Use of your information</h3>
          <p>
            Having accurate information about you, permits us to provide you
            with a smooth, efficient, and customised experience. specifically,
            we may use information collected about you via the site:
          </p>
          <ul>
            <li>
              to provide and maintain our service, including to monitor the
              usage of our service.
            </li>
            <li>
              to manage your account: to manage your registration as a user of
              the service.
            </li>
            <li>
              the personal data you provide can give you access to different
              functionalities of the service that are available to you as a
              registered user.
            </li>
            <li>
              for the performance of a contract: the development, compliance and
              undertaking of the purchase contract for the products, items or
              services you have purchased or of any other contract with us
              through the service.
            </li>
            <li>
              to contact you: to contact you by email, telephone calls, sms, or
              other equivalent forms of electronic communication, such as a
              mobile application's push notifications regarding updates or
              informative communications related to the functionalities,
              products or contracted services, including the security updates,
              when necessary or reasonable for their implementation.
            </li>
            <li>
              to provide you with relevant news and general information about
              our services.
            </li>
            <li>
              to manage your requests: to attend and manage your requests to us.
            </li>
          </ul>
          <h3>
            Legal basis for processing personal data under general data
            protection regulation (gdpr)
          </h3>
          <p>
            If you are from the european economic area (eea), Acter’s legal
            basis for collecting and using the personal information described in
            this privacy policy depends on the personal data we collect and the
            specific context in which we collect it.
          </p>
          <p>acter may process your personal data because:</p>
          <ul>
            <li>we need to perform a contract with you</li>
            <li>you have given us permission to do so</li>
            <li>
              the processing is in our legitimate interests and it’s not
              overridden by your rights
            </li>
            <li>for payment processing purposes</li>
            <li>to comply with the law</li>
          </ul>
          <h3>​Retention of your personal data</h3>
          <p>
            The company will retain your personal data only for as long as is
            necessary for the purposes set out in this privacy policy. we will
            retain and use your personal data to the extent necessary to comply
            with our legal obligations (for example, if we are required to
            retain your data to comply with applicable laws), resolve disputes,
            and enforce our legal agreements and policies. the company will also
            retain usage data for internal analysis purposes. usage data is
            generally retained for a shorter period of time, except when this
            data is used to strengthen the security or to improve the
            functionality of our service, or we are legally obligated to retain
            this data for longer time periods.
          </p>
          <h3>Transfer of data</h3>
          <p>
            Your information, including personal data, may be transferred to —
            and maintained on — computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ than those from your jurisdiction. your
            consent to this privacy policy followed by your submission of such
            information represents your agreement to that transfer. Acter will
            take all steps reasonably necessary to ensure that your data is
            treated securely and in accordance with this privacy policy and no
            transfer of your personal data will take place to an organization or
            a country unless there are adequate controls in place including the
            security of your data and other personal information.
          </p>
          <h3>​Disclosure of your information</h3>
          <p>
            When you create an account on acter, you create a profile that is
            made available to other registered accounts/profiles and our service
            allows you to connect with other profiles. This profile includes
            personal information such as your name, location, photo of you,
            affiliated organisations and activities, and any other information
            you chose to make public. acter does not disclose any of your
            personal data with any outside organizations for purposes other than
            web hosting or analytics, nor will we sell your data to anybody.
          </p>
          <h3>Law enforcement</h3>
          <p>
            Under certain circumstances we may be required to disclose your
            personal information to third parties (such as public authorities)
            in order to: comply with laws, regulations, legal process, or
            enforceable government requests; protect, defend or assert your
            legal rights regarding your personal safety; or to prevent or
            investigate possible wrongdoing connected with the use of our
            website and its services (such as criminal activity, fraud and
            misuse or unauthorized use of our website).
          </p>
          <h3>Other legal requirements</h3>
          <p>
            The company may disclose your personal data in the good faith belief
            that such action is necessary to:
          </p>
          <ul>
            <li>comply with a legal obligation</li>
            <li>protect and defend the rights or property of the company</li>
            <li>
              prevent or investigate possible wrongdoing in connection with the
              service
            </li>{' '}
            <li>
              protect the personal safety of users of the service or the public
            </li>{' '}
            <li>protect against legal liability</li>
          </ul>
          ​<h3>Security of your information</h3>
          <p>
            We use administrative, technical, and physical security measures to
            help protect your personal information. While we have taken
            reasonable steps to secure the personal information you provide to
            us, please be aware that despite our efforts, no security measures
            are perfect or impenetrable, and no method of data transmission can
            be guaranteed against any interception or other type of misuse. any
            information disclosed online is vulnerable to interception and
            misuse by unauthorised parties. therefore, we cannot guarantee
            complete security if you provide personal information.
          </p>
          <h3>
            Your data protection rights under general data protection regulation
            (gdpr)
          </h3>
          <p>
            If you are a resident of the european economic area (eea), you have
            certain data protection rights. Acter aims to take reasonable steps
            to allow you to correct, amend, delete, or limit the use of your
            personal data. If you wish to be informed what personal data we hold
            about you and if you want it to be removed from our systems, please
            contact us.
          </p>
          <p>
            in certain circumstances, you have the following data protection
            rights:
          </p>
          <ul>
            <li>
              the right to access, update or to delete the information we have
              on you. whenever made possible, you can access, update or request
              deletion of your personal data directly within your account
              settings section. If you are unable to perform these actions
              yourself, please contact us to assist you.
            </li>{' '}
            <li>
              the right of rectification. you have the right to have your
              information rectified if that information is inaccurate or
              incomplete.
            </li>{' '}
            <li>
              the right to object. you have the right to object to our
              processing of your personal data.
            </li>{' '}
            <li>
              the right of restriction. you have the right to request that we
              restrict the processing of your personal information.
            </li>
            <li>
              the right to data portability. you have the right to be provided
              with a copy of the information we have on you in a structured,
              machine-readable and commonly used format.
            </li>{' '}
            <li>
              the right to withdraw consent. you also have the right to withdraw
              your consent at any time where Acter relied on your consent to
              process your personal information.
            </li>
          </ul>
          <p>
            Please note that we may ask you to verify your identity before
            responding to such requests. you have the right to complain to a
            data protection authority about our collection and use of your
            personal data. for more information, please contact your local data
            protection authority in the european economic area (eea).
          </p>
          <h3>Links to other web applications</h3>
          <p>
            Our service may contain links to other web applications that are not
            operated by us. if you click on a third party link, you will be
            directed to that third party's site. we strongly advise you to
            review the privacy policy of every site you visit. we have no
            control over and assume no responsibility for the content, privacy
            policies or practices of any third party sites or services.
          </p>
          <h3>Policy for children</h3>
          <p>
            We do not knowingly solicit information from or service to children
            under the age of 13. If you become aware of any data we have
            collected from children under age 13, please contact us using the
            contact information provided below.
          </p>
          <h3>Service providers (3rd party providers)</h3>
          <p>
            We may employ third party companies and individuals to facilitate
            our service (“service providers”), to provide the service on our
            behalf, to perform service-related services or to assist us in
            analyzing how our service is used.
          </p>
          <p>
            These third parties have access to your personal data only to
            perform these tasks on our behalf and are obligated not to disclose
            or use it for any other purpose.
          </p>
          <p>
            Example of service providers we use include, but are not limited to:
          </p>
          <ul>
            <li>DigitalOcean</li>
            <li>SendGrid</li>
            <li>Facebook</li> <li>LinkedIn</li>
          </ul>
          <h3>Changes to this privacy policy</h3>
          <p>
            We may update our privacy policy from time to time. we will notify
            you of any changes by posting the new privacy policy on this page.
            We will let you know via email and/or a prominent notice on our
            service, prior to the change becoming effective and update the "last
            updated" date at the top of this privacy policy. you are advised to
            review this privacy policy periodically for any changes. changes to
            this privacy policy are effective when they are posted on this page.
          </p>
          <h3>Contact us</h3>
          <p>
            If you have any questions about this privacy policy, please contact
            us at:
          </p>
          <p>
            <strong>Acter aps</strong> <br />
            Fiskerivej 2h <br />
            8000 Aarhus Denmark <br />
            Phone: +45 91 53 01 08 <br />
            Email: hello@acter.global
          </p>
        </div>
      </main>
    </Layout>
  )
}

export default GDPR
