import { ActerConnectionListRelationFilter } from "../inputs/ActerConnectionListRelationFilter";
import { ActerInterestListRelationFilter } from "../inputs/ActerInterestListRelationFilter";
import { ActerListRelationFilter } from "../inputs/ActerListRelationFilter";
import { ActerRelationFilter } from "../inputs/ActerRelationFilter";
import { ActerTypeRelationFilter } from "../inputs/ActerTypeRelationFilter";
import { ActivityListRelationFilter } from "../inputs/ActivityListRelationFilter";
import { ActivityRelationFilter } from "../inputs/ActivityRelationFilter";
import { BoolFilter } from "../inputs/BoolFilter";
import { DateTimeFilter } from "../inputs/DateTimeFilter";
import { DateTimeNullableFilter } from "../inputs/DateTimeNullableFilter";
import { FloatNullableFilter } from "../inputs/FloatNullableFilter";
import { StringFilter } from "../inputs/StringFilter";
import { StringNullableFilter } from "../inputs/StringNullableFilter";
import { UserRelationFilter } from "../inputs/UserRelationFilter";
export declare class ActerWhereInput {
    AND?: ActerWhereInput[] | undefined;
    OR?: ActerWhereInput[] | undefined;
    NOT?: ActerWhereInput[] | undefined;
    id?: StringFilter | undefined;
    acterTypeId?: StringFilter | undefined;
    name?: StringNullableFilter | undefined;
    slug?: StringNullableFilter | undefined;
    description?: StringNullableFilter | undefined;
    location?: StringNullableFilter | undefined;
    locationLat?: FloatNullableFilter | undefined;
    locationLng?: FloatNullableFilter | undefined;
    url?: StringNullableFilter | undefined;
    avatarUrl?: StringNullableFilter | undefined;
    bannerUrl?: StringNullableFilter | undefined;
    autoApproveFollowers?: BoolFilter | undefined;
    createdAt?: DateTimeFilter | undefined;
    updatedAt?: DateTimeFilter | undefined;
    createdByUser?: UserRelationFilter | undefined;
    createdByUserId?: StringFilter | undefined;
    deletedAt?: DateTimeNullableFilter | undefined;
    deltedByUserId?: StringNullableFilter | undefined;
    DeletedByUser?: UserRelationFilter | undefined;
    ActerType?: ActerTypeRelationFilter | undefined;
    Parent?: ActerRelationFilter | undefined;
    Children?: ActerListRelationFilter | undefined;
    parentActerId?: StringNullableFilter | undefined;
    Following?: ActerConnectionListRelationFilter | undefined;
    Followers?: ActerConnectionListRelationFilter | undefined;
    User?: UserRelationFilter | undefined;
    ActerInterests?: ActerInterestListRelationFilter | undefined;
    Activity?: ActivityRelationFilter | undefined;
    ActivitiesOrganized?: ActivityListRelationFilter | undefined;
}
