"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertInterestTypeArgs = exports.UpdateManyInterestTypeArgs = exports.UpdateInterestTypeArgs = exports.FindUniqueInterestTypeArgs = exports.FindManyInterestTypeArgs = exports.FindFirstInterestTypeArgs = exports.DeleteManyInterestTypeArgs = exports.DeleteInterestTypeArgs = exports.CreateInterestTypeArgs = exports.AggregateInterestTypeArgs = void 0;
var AggregateInterestTypeArgs_1 = require("./AggregateInterestTypeArgs");
Object.defineProperty(exports, "AggregateInterestTypeArgs", { enumerable: true, get: function () { return AggregateInterestTypeArgs_1.AggregateInterestTypeArgs; } });
var CreateInterestTypeArgs_1 = require("./CreateInterestTypeArgs");
Object.defineProperty(exports, "CreateInterestTypeArgs", { enumerable: true, get: function () { return CreateInterestTypeArgs_1.CreateInterestTypeArgs; } });
var DeleteInterestTypeArgs_1 = require("./DeleteInterestTypeArgs");
Object.defineProperty(exports, "DeleteInterestTypeArgs", { enumerable: true, get: function () { return DeleteInterestTypeArgs_1.DeleteInterestTypeArgs; } });
var DeleteManyInterestTypeArgs_1 = require("./DeleteManyInterestTypeArgs");
Object.defineProperty(exports, "DeleteManyInterestTypeArgs", { enumerable: true, get: function () { return DeleteManyInterestTypeArgs_1.DeleteManyInterestTypeArgs; } });
var FindFirstInterestTypeArgs_1 = require("./FindFirstInterestTypeArgs");
Object.defineProperty(exports, "FindFirstInterestTypeArgs", { enumerable: true, get: function () { return FindFirstInterestTypeArgs_1.FindFirstInterestTypeArgs; } });
var FindManyInterestTypeArgs_1 = require("./FindManyInterestTypeArgs");
Object.defineProperty(exports, "FindManyInterestTypeArgs", { enumerable: true, get: function () { return FindManyInterestTypeArgs_1.FindManyInterestTypeArgs; } });
var FindUniqueInterestTypeArgs_1 = require("./FindUniqueInterestTypeArgs");
Object.defineProperty(exports, "FindUniqueInterestTypeArgs", { enumerable: true, get: function () { return FindUniqueInterestTypeArgs_1.FindUniqueInterestTypeArgs; } });
var UpdateInterestTypeArgs_1 = require("./UpdateInterestTypeArgs");
Object.defineProperty(exports, "UpdateInterestTypeArgs", { enumerable: true, get: function () { return UpdateInterestTypeArgs_1.UpdateInterestTypeArgs; } });
var UpdateManyInterestTypeArgs_1 = require("./UpdateManyInterestTypeArgs");
Object.defineProperty(exports, "UpdateManyInterestTypeArgs", { enumerable: true, get: function () { return UpdateManyInterestTypeArgs_1.UpdateManyInterestTypeArgs; } });
var UpsertInterestTypeArgs_1 = require("./UpsertInterestTypeArgs");
Object.defineProperty(exports, "UpsertInterestTypeArgs", { enumerable: true, get: function () { return UpsertInterestTypeArgs_1.UpsertInterestTypeArgs; } });
