"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertActivityTypeArgs = exports.UpdateManyActivityTypeArgs = exports.UpdateActivityTypeArgs = exports.GroupByActivityTypeArgs = exports.FindUniqueActivityTypeArgs = exports.FindManyActivityTypeArgs = exports.FindFirstActivityTypeArgs = exports.DeleteManyActivityTypeArgs = exports.DeleteActivityTypeArgs = exports.CreateManyActivityTypeArgs = exports.CreateActivityTypeArgs = exports.AggregateActivityTypeArgs = void 0;
var AggregateActivityTypeArgs_1 = require("./AggregateActivityTypeArgs");
Object.defineProperty(exports, "AggregateActivityTypeArgs", { enumerable: true, get: function () { return AggregateActivityTypeArgs_1.AggregateActivityTypeArgs; } });
var CreateActivityTypeArgs_1 = require("./CreateActivityTypeArgs");
Object.defineProperty(exports, "CreateActivityTypeArgs", { enumerable: true, get: function () { return CreateActivityTypeArgs_1.CreateActivityTypeArgs; } });
var CreateManyActivityTypeArgs_1 = require("./CreateManyActivityTypeArgs");
Object.defineProperty(exports, "CreateManyActivityTypeArgs", { enumerable: true, get: function () { return CreateManyActivityTypeArgs_1.CreateManyActivityTypeArgs; } });
var DeleteActivityTypeArgs_1 = require("./DeleteActivityTypeArgs");
Object.defineProperty(exports, "DeleteActivityTypeArgs", { enumerable: true, get: function () { return DeleteActivityTypeArgs_1.DeleteActivityTypeArgs; } });
var DeleteManyActivityTypeArgs_1 = require("./DeleteManyActivityTypeArgs");
Object.defineProperty(exports, "DeleteManyActivityTypeArgs", { enumerable: true, get: function () { return DeleteManyActivityTypeArgs_1.DeleteManyActivityTypeArgs; } });
var FindFirstActivityTypeArgs_1 = require("./FindFirstActivityTypeArgs");
Object.defineProperty(exports, "FindFirstActivityTypeArgs", { enumerable: true, get: function () { return FindFirstActivityTypeArgs_1.FindFirstActivityTypeArgs; } });
var FindManyActivityTypeArgs_1 = require("./FindManyActivityTypeArgs");
Object.defineProperty(exports, "FindManyActivityTypeArgs", { enumerable: true, get: function () { return FindManyActivityTypeArgs_1.FindManyActivityTypeArgs; } });
var FindUniqueActivityTypeArgs_1 = require("./FindUniqueActivityTypeArgs");
Object.defineProperty(exports, "FindUniqueActivityTypeArgs", { enumerable: true, get: function () { return FindUniqueActivityTypeArgs_1.FindUniqueActivityTypeArgs; } });
var GroupByActivityTypeArgs_1 = require("./GroupByActivityTypeArgs");
Object.defineProperty(exports, "GroupByActivityTypeArgs", { enumerable: true, get: function () { return GroupByActivityTypeArgs_1.GroupByActivityTypeArgs; } });
var UpdateActivityTypeArgs_1 = require("./UpdateActivityTypeArgs");
Object.defineProperty(exports, "UpdateActivityTypeArgs", { enumerable: true, get: function () { return UpdateActivityTypeArgs_1.UpdateActivityTypeArgs; } });
var UpdateManyActivityTypeArgs_1 = require("./UpdateManyActivityTypeArgs");
Object.defineProperty(exports, "UpdateManyActivityTypeArgs", { enumerable: true, get: function () { return UpdateManyActivityTypeArgs_1.UpdateManyActivityTypeArgs; } });
var UpsertActivityTypeArgs_1 = require("./UpsertActivityTypeArgs");
Object.defineProperty(exports, "UpsertActivityTypeArgs", { enumerable: true, get: function () { return UpsertActivityTypeArgs_1.UpsertActivityTypeArgs; } });
