import { ActerConnection } from "../models/ActerConnection";
import { ActerInterest } from "../models/ActerInterest";
import { ActerType } from "../models/ActerType";
import { Activity } from "../models/Activity";
import { Link } from "../models/Link";
import { Post } from "../models/Post";
import { User } from "../models/User";
export declare class Acter {
    id: string;
    acterTypeId: string;
    name?: string | null;
    slug?: string | null;
    description?: string | null;
    location?: string | null;
    locationLat?: number | null;
    locationLng?: number | null;
    url?: string | null;
    avatarUrl?: string | null;
    bannerUrl?: string | null;
    useAdmins: boolean;
    createdAt: Date;
    updatedAt: Date;
    acterJoinSetting: "EVERYONE" | "RESTRICTED" | "INVITE_ONLY";
    ActerInterests?: ActerInterest[];
    createdByUser?: User;
    createdByUserId: string;
    deletedAt?: Date | null;
    deltedByUserId?: string | null;
    DeletedByUser?: User | null;
    ActerType?: ActerType;
    Parent?: Acter | null;
    Children?: Acter[];
    parentActerId?: string | null;
    Following?: ActerConnection[];
    Followers?: ActerConnection[];
    User?: User | null;
    Activity?: Activity | null;
    ActivitiesOrganized?: Activity[];
    AttachedPosts?: Post[];
    AuthoredPosts?: Post[];
    AttachedLinks?: Link[];
}
