export declare enum ActerScalarFieldEnum {
    id = "id",
    acterTypeId = "acterTypeId",
    name = "name",
    slug = "slug",
    description = "description",
    location = "location",
    locationLat = "locationLat",
    locationLng = "locationLng",
    url = "url",
    avatarUrl = "avatarUrl",
    bannerUrl = "bannerUrl",
    useAdmins = "useAdmins",
    createdAt = "createdAt",
    updatedAt = "updatedAt",
    acterJoinSetting = "acterJoinSetting",
    createdByUserId = "createdByUserId",
    deletedAt = "deletedAt",
    deltedByUserId = "deltedByUserId",
    parentActerId = "parentActerId"
}
