"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertNotificationArgs = exports.UpdateNotificationArgs = exports.UpdateManyNotificationArgs = exports.GroupByNotificationArgs = exports.FindUniqueNotificationArgs = exports.FindManyNotificationArgs = exports.FindFirstNotificationArgs = exports.DeleteNotificationArgs = exports.DeleteManyNotificationArgs = exports.CreateNotificationArgs = exports.CreateManyNotificationArgs = exports.AggregateNotificationArgs = void 0;
var AggregateNotificationArgs_1 = require("./AggregateNotificationArgs");
Object.defineProperty(exports, "AggregateNotificationArgs", { enumerable: true, get: function () { return AggregateNotificationArgs_1.AggregateNotificationArgs; } });
var CreateManyNotificationArgs_1 = require("./CreateManyNotificationArgs");
Object.defineProperty(exports, "CreateManyNotificationArgs", { enumerable: true, get: function () { return CreateManyNotificationArgs_1.CreateManyNotificationArgs; } });
var CreateNotificationArgs_1 = require("./CreateNotificationArgs");
Object.defineProperty(exports, "CreateNotificationArgs", { enumerable: true, get: function () { return CreateNotificationArgs_1.CreateNotificationArgs; } });
var DeleteManyNotificationArgs_1 = require("./DeleteManyNotificationArgs");
Object.defineProperty(exports, "DeleteManyNotificationArgs", { enumerable: true, get: function () { return DeleteManyNotificationArgs_1.DeleteManyNotificationArgs; } });
var DeleteNotificationArgs_1 = require("./DeleteNotificationArgs");
Object.defineProperty(exports, "DeleteNotificationArgs", { enumerable: true, get: function () { return DeleteNotificationArgs_1.DeleteNotificationArgs; } });
var FindFirstNotificationArgs_1 = require("./FindFirstNotificationArgs");
Object.defineProperty(exports, "FindFirstNotificationArgs", { enumerable: true, get: function () { return FindFirstNotificationArgs_1.FindFirstNotificationArgs; } });
var FindManyNotificationArgs_1 = require("./FindManyNotificationArgs");
Object.defineProperty(exports, "FindManyNotificationArgs", { enumerable: true, get: function () { return FindManyNotificationArgs_1.FindManyNotificationArgs; } });
var FindUniqueNotificationArgs_1 = require("./FindUniqueNotificationArgs");
Object.defineProperty(exports, "FindUniqueNotificationArgs", { enumerable: true, get: function () { return FindUniqueNotificationArgs_1.FindUniqueNotificationArgs; } });
var GroupByNotificationArgs_1 = require("./GroupByNotificationArgs");
Object.defineProperty(exports, "GroupByNotificationArgs", { enumerable: true, get: function () { return GroupByNotificationArgs_1.GroupByNotificationArgs; } });
var UpdateManyNotificationArgs_1 = require("./UpdateManyNotificationArgs");
Object.defineProperty(exports, "UpdateManyNotificationArgs", { enumerable: true, get: function () { return UpdateManyNotificationArgs_1.UpdateManyNotificationArgs; } });
var UpdateNotificationArgs_1 = require("./UpdateNotificationArgs");
Object.defineProperty(exports, "UpdateNotificationArgs", { enumerable: true, get: function () { return UpdateNotificationArgs_1.UpdateNotificationArgs; } });
var UpsertNotificationArgs_1 = require("./UpsertNotificationArgs");
Object.defineProperty(exports, "UpsertNotificationArgs", { enumerable: true, get: function () { return UpsertNotificationArgs_1.UpsertNotificationArgs; } });
