"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertInviteArgs = exports.UpdateManyInviteArgs = exports.UpdateInviteArgs = exports.GroupByInviteArgs = exports.FindUniqueInviteArgs = exports.FindManyInviteArgs = exports.FindFirstInviteArgs = exports.DeleteManyInviteArgs = exports.DeleteInviteArgs = exports.CreateManyInviteArgs = exports.CreateInviteArgs = exports.AggregateInviteArgs = void 0;
var AggregateInviteArgs_1 = require("./AggregateInviteArgs");
Object.defineProperty(exports, "AggregateInviteArgs", { enumerable: true, get: function () { return AggregateInviteArgs_1.AggregateInviteArgs; } });
var CreateInviteArgs_1 = require("./CreateInviteArgs");
Object.defineProperty(exports, "CreateInviteArgs", { enumerable: true, get: function () { return CreateInviteArgs_1.CreateInviteArgs; } });
var CreateManyInviteArgs_1 = require("./CreateManyInviteArgs");
Object.defineProperty(exports, "CreateManyInviteArgs", { enumerable: true, get: function () { return CreateManyInviteArgs_1.CreateManyInviteArgs; } });
var DeleteInviteArgs_1 = require("./DeleteInviteArgs");
Object.defineProperty(exports, "DeleteInviteArgs", { enumerable: true, get: function () { return DeleteInviteArgs_1.DeleteInviteArgs; } });
var DeleteManyInviteArgs_1 = require("./DeleteManyInviteArgs");
Object.defineProperty(exports, "DeleteManyInviteArgs", { enumerable: true, get: function () { return DeleteManyInviteArgs_1.DeleteManyInviteArgs; } });
var FindFirstInviteArgs_1 = require("./FindFirstInviteArgs");
Object.defineProperty(exports, "FindFirstInviteArgs", { enumerable: true, get: function () { return FindFirstInviteArgs_1.FindFirstInviteArgs; } });
var FindManyInviteArgs_1 = require("./FindManyInviteArgs");
Object.defineProperty(exports, "FindManyInviteArgs", { enumerable: true, get: function () { return FindManyInviteArgs_1.FindManyInviteArgs; } });
var FindUniqueInviteArgs_1 = require("./FindUniqueInviteArgs");
Object.defineProperty(exports, "FindUniqueInviteArgs", { enumerable: true, get: function () { return FindUniqueInviteArgs_1.FindUniqueInviteArgs; } });
var GroupByInviteArgs_1 = require("./GroupByInviteArgs");
Object.defineProperty(exports, "GroupByInviteArgs", { enumerable: true, get: function () { return GroupByInviteArgs_1.GroupByInviteArgs; } });
var UpdateInviteArgs_1 = require("./UpdateInviteArgs");
Object.defineProperty(exports, "UpdateInviteArgs", { enumerable: true, get: function () { return UpdateInviteArgs_1.UpdateInviteArgs; } });
var UpdateManyInviteArgs_1 = require("./UpdateManyInviteArgs");
Object.defineProperty(exports, "UpdateManyInviteArgs", { enumerable: true, get: function () { return UpdateManyInviteArgs_1.UpdateManyInviteArgs; } });
var UpsertInviteArgs_1 = require("./UpsertInviteArgs");
Object.defineProperty(exports, "UpsertInviteArgs", { enumerable: true, get: function () { return UpsertInviteArgs_1.UpsertInviteArgs; } });
