"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserRelationsResolver = exports.PostRelationsResolver = exports.NotificationRelationsResolver = exports.LinkRelationsResolver = exports.InviteRelationsResolver = exports.InterestTypeRelationsResolver = exports.InterestRelationsResolver = exports.ActivityTypeRelationsResolver = exports.ActivityRelationsResolver = exports.ActerTypeRuleRelationsResolver = exports.ActerTypeRelationsResolver = exports.ActerInterestRelationsResolver = exports.ActerConnectionRelationsResolver = exports.ActerRelationsResolver = void 0;
var ActerRelationsResolver_1 = require("./Acter/ActerRelationsResolver");
Object.defineProperty(exports, "ActerRelationsResolver", { enumerable: true, get: function () { return ActerRelationsResolver_1.ActerRelationsResolver; } });
var ActerConnectionRelationsResolver_1 = require("./ActerConnection/ActerConnectionRelationsResolver");
Object.defineProperty(exports, "ActerConnectionRelationsResolver", { enumerable: true, get: function () { return ActerConnectionRelationsResolver_1.ActerConnectionRelationsResolver; } });
var ActerInterestRelationsResolver_1 = require("./ActerInterest/ActerInterestRelationsResolver");
Object.defineProperty(exports, "ActerInterestRelationsResolver", { enumerable: true, get: function () { return ActerInterestRelationsResolver_1.ActerInterestRelationsResolver; } });
var ActerTypeRelationsResolver_1 = require("./ActerType/ActerTypeRelationsResolver");
Object.defineProperty(exports, "ActerTypeRelationsResolver", { enumerable: true, get: function () { return ActerTypeRelationsResolver_1.ActerTypeRelationsResolver; } });
var ActerTypeRuleRelationsResolver_1 = require("./ActerTypeRule/ActerTypeRuleRelationsResolver");
Object.defineProperty(exports, "ActerTypeRuleRelationsResolver", { enumerable: true, get: function () { return ActerTypeRuleRelationsResolver_1.ActerTypeRuleRelationsResolver; } });
var ActivityRelationsResolver_1 = require("./Activity/ActivityRelationsResolver");
Object.defineProperty(exports, "ActivityRelationsResolver", { enumerable: true, get: function () { return ActivityRelationsResolver_1.ActivityRelationsResolver; } });
var ActivityTypeRelationsResolver_1 = require("./ActivityType/ActivityTypeRelationsResolver");
Object.defineProperty(exports, "ActivityTypeRelationsResolver", { enumerable: true, get: function () { return ActivityTypeRelationsResolver_1.ActivityTypeRelationsResolver; } });
var InterestRelationsResolver_1 = require("./Interest/InterestRelationsResolver");
Object.defineProperty(exports, "InterestRelationsResolver", { enumerable: true, get: function () { return InterestRelationsResolver_1.InterestRelationsResolver; } });
var InterestTypeRelationsResolver_1 = require("./InterestType/InterestTypeRelationsResolver");
Object.defineProperty(exports, "InterestTypeRelationsResolver", { enumerable: true, get: function () { return InterestTypeRelationsResolver_1.InterestTypeRelationsResolver; } });
var InviteRelationsResolver_1 = require("./Invite/InviteRelationsResolver");
Object.defineProperty(exports, "InviteRelationsResolver", { enumerable: true, get: function () { return InviteRelationsResolver_1.InviteRelationsResolver; } });
var LinkRelationsResolver_1 = require("./Link/LinkRelationsResolver");
Object.defineProperty(exports, "LinkRelationsResolver", { enumerable: true, get: function () { return LinkRelationsResolver_1.LinkRelationsResolver; } });
var NotificationRelationsResolver_1 = require("./Notification/NotificationRelationsResolver");
Object.defineProperty(exports, "NotificationRelationsResolver", { enumerable: true, get: function () { return NotificationRelationsResolver_1.NotificationRelationsResolver; } });
var PostRelationsResolver_1 = require("./Post/PostRelationsResolver");
Object.defineProperty(exports, "PostRelationsResolver", { enumerable: true, get: function () { return PostRelationsResolver_1.PostRelationsResolver; } });
var UserRelationsResolver_1 = require("./User/UserRelationsResolver");
Object.defineProperty(exports, "UserRelationsResolver", { enumerable: true, get: function () { return UserRelationsResolver_1.UserRelationsResolver; } });
