"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertInterestArgs = exports.UpdateManyInterestArgs = exports.UpdateInterestArgs = exports.FindUniqueInterestArgs = exports.FindManyInterestArgs = exports.FindFirstInterestArgs = exports.DeleteManyInterestArgs = exports.DeleteInterestArgs = exports.CreateInterestArgs = exports.AggregateInterestArgs = void 0;
var AggregateInterestArgs_1 = require("./AggregateInterestArgs");
Object.defineProperty(exports, "AggregateInterestArgs", { enumerable: true, get: function () { return AggregateInterestArgs_1.AggregateInterestArgs; } });
var CreateInterestArgs_1 = require("./CreateInterestArgs");
Object.defineProperty(exports, "CreateInterestArgs", { enumerable: true, get: function () { return CreateInterestArgs_1.CreateInterestArgs; } });
var DeleteInterestArgs_1 = require("./DeleteInterestArgs");
Object.defineProperty(exports, "DeleteInterestArgs", { enumerable: true, get: function () { return DeleteInterestArgs_1.DeleteInterestArgs; } });
var DeleteManyInterestArgs_1 = require("./DeleteManyInterestArgs");
Object.defineProperty(exports, "DeleteManyInterestArgs", { enumerable: true, get: function () { return DeleteManyInterestArgs_1.DeleteManyInterestArgs; } });
var FindFirstInterestArgs_1 = require("./FindFirstInterestArgs");
Object.defineProperty(exports, "FindFirstInterestArgs", { enumerable: true, get: function () { return FindFirstInterestArgs_1.FindFirstInterestArgs; } });
var FindManyInterestArgs_1 = require("./FindManyInterestArgs");
Object.defineProperty(exports, "FindManyInterestArgs", { enumerable: true, get: function () { return FindManyInterestArgs_1.FindManyInterestArgs; } });
var FindUniqueInterestArgs_1 = require("./FindUniqueInterestArgs");
Object.defineProperty(exports, "FindUniqueInterestArgs", { enumerable: true, get: function () { return FindUniqueInterestArgs_1.FindUniqueInterestArgs; } });
var UpdateInterestArgs_1 = require("./UpdateInterestArgs");
Object.defineProperty(exports, "UpdateInterestArgs", { enumerable: true, get: function () { return UpdateInterestArgs_1.UpdateInterestArgs; } });
var UpdateManyInterestArgs_1 = require("./UpdateManyInterestArgs");
Object.defineProperty(exports, "UpdateManyInterestArgs", { enumerable: true, get: function () { return UpdateManyInterestArgs_1.UpdateManyInterestArgs; } });
var UpsertInterestArgs_1 = require("./UpsertInterestArgs");
Object.defineProperty(exports, "UpsertInterestArgs", { enumerable: true, get: function () { return UpsertInterestArgs_1.UpsertInterestArgs; } });
