"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertLinkArgs = exports.UpdateManyLinkArgs = exports.UpdateLinkArgs = exports.GroupByLinkArgs = exports.FindUniqueLinkArgs = exports.FindManyLinkArgs = exports.FindFirstLinkArgs = exports.DeleteManyLinkArgs = exports.DeleteLinkArgs = exports.CreateManyLinkArgs = exports.CreateLinkArgs = exports.AggregateLinkArgs = void 0;
var AggregateLinkArgs_1 = require("./AggregateLinkArgs");
Object.defineProperty(exports, "AggregateLinkArgs", { enumerable: true, get: function () { return AggregateLinkArgs_1.AggregateLinkArgs; } });
var CreateLinkArgs_1 = require("./CreateLinkArgs");
Object.defineProperty(exports, "CreateLinkArgs", { enumerable: true, get: function () { return CreateLinkArgs_1.CreateLinkArgs; } });
var CreateManyLinkArgs_1 = require("./CreateManyLinkArgs");
Object.defineProperty(exports, "CreateManyLinkArgs", { enumerable: true, get: function () { return CreateManyLinkArgs_1.CreateManyLinkArgs; } });
var DeleteLinkArgs_1 = require("./DeleteLinkArgs");
Object.defineProperty(exports, "DeleteLinkArgs", { enumerable: true, get: function () { return DeleteLinkArgs_1.DeleteLinkArgs; } });
var DeleteManyLinkArgs_1 = require("./DeleteManyLinkArgs");
Object.defineProperty(exports, "DeleteManyLinkArgs", { enumerable: true, get: function () { return DeleteManyLinkArgs_1.DeleteManyLinkArgs; } });
var FindFirstLinkArgs_1 = require("./FindFirstLinkArgs");
Object.defineProperty(exports, "FindFirstLinkArgs", { enumerable: true, get: function () { return FindFirstLinkArgs_1.FindFirstLinkArgs; } });
var FindManyLinkArgs_1 = require("./FindManyLinkArgs");
Object.defineProperty(exports, "FindManyLinkArgs", { enumerable: true, get: function () { return FindManyLinkArgs_1.FindManyLinkArgs; } });
var FindUniqueLinkArgs_1 = require("./FindUniqueLinkArgs");
Object.defineProperty(exports, "FindUniqueLinkArgs", { enumerable: true, get: function () { return FindUniqueLinkArgs_1.FindUniqueLinkArgs; } });
var GroupByLinkArgs_1 = require("./GroupByLinkArgs");
Object.defineProperty(exports, "GroupByLinkArgs", { enumerable: true, get: function () { return GroupByLinkArgs_1.GroupByLinkArgs; } });
var UpdateLinkArgs_1 = require("./UpdateLinkArgs");
Object.defineProperty(exports, "UpdateLinkArgs", { enumerable: true, get: function () { return UpdateLinkArgs_1.UpdateLinkArgs; } });
var UpdateManyLinkArgs_1 = require("./UpdateManyLinkArgs");
Object.defineProperty(exports, "UpdateManyLinkArgs", { enumerable: true, get: function () { return UpdateManyLinkArgs_1.UpdateManyLinkArgs; } });
var UpsertLinkArgs_1 = require("./UpsertLinkArgs");
Object.defineProperty(exports, "UpsertLinkArgs", { enumerable: true, get: function () { return UpsertLinkArgs_1.UpsertLinkArgs; } });
