name: Tag to Production

on:
  push:
    tags:
      - '**'

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'main'
          TO_BRANCH: 'production'
          PULL_REQUEST_TITLE: 'Release ${{github.ref_name}} to Production'
          PULL_REQUEST_BODY: 'Tag ${{github.ref_name}} from main is ready for production'
          TEAM_REVIEWERS: '["acterglobal/eng"]'
