# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Run test coverage on each push

on: push

jobs:
  lint-cover-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2.1.4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Set Prisma TypeGraphQL generated files path
        run: |
          echo "TYPEGRAPHQL_OUTPUT=\"../@generated/type-graphql\"" >> $GITHUB_ENV

      - name: yarn install
        run: |
          yarn
      
      - name: lint
        run: |
          yarn lint

      - name: coverage tests
        run: |
          yarn cover
      
      - name: build
        run: |
          yarn build
      
