# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Run test coverage on each push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: yarn install
        run: |
          yarn

      - name: generate schema
        run: |
          yarn workspace @acter/schema build

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: lint
        run: |
          yarn lint

  cover:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: coverage tests
        run: |
          yarn cover

  build-web:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: build web
        run: |
          yarn workspace @acter/web build
