# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Run test coverage on each push

on: push

env:
  NEXT_PUBLIC_IMAGE_LOADER_URL: https://acter-dev.imgix.net

jobs:
  checkout-install-schema:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Set up Next.js build cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/packages/web/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]sx?') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: yarn install
        run: |
          yarn

      - name: generate schema
        run: |
          yarn workspace @acter/schema build

      - name: zip
        run: tar --exclude='./.git' --exclude='./.yarn/cache' -zcf /tmp/workspace.tar.gz .

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: workspace
          path: /tmp/workspace.tar.gz

  lint:
    runs-on: ubuntu-latest
    needs: checkout-install-schema
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: workspace
          path: /tmp

      - name: unzip
        run: tar -tf /tmp/workspace.tar.gz

      - name: lint
        run: |
          yarn lint

  test-cover:
    runs-on: ubuntu-latest
    needs: checkout-install-schema
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: workspace
          path: /tmp

      - name: unzip
        run: tar -tf /tmp/workspace.tar.gz

      - name: coverage tests
        run: |
          yarn cover

  build-web:
    runs-on: ubuntu-latest
    needs: checkout-install-schema
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: workspace
          path: /tmp

      - name: unzip
        run: tar -tf /tmp/workspace.tar.gz

      - name: build web
        run: |
          yarn workspace @acter/web build
